### ISSUE TITLE
https://www.ebi.ac.uk/ena/software/flat-file-validator missing GitHub link

### ISSUE THREAD

**Issue by peterjc** [enasequence/sequencetools#1]
The validator home page https://www.ebi.ac.uk/ena/software/flat-file-validator has a link to Maven Central, but is missing a link to this GitHub repository.

**Comment by raskoleinonen** [comment]
Dear Peter,

I have added the link.

Best,

Rasko

**Comment by peterjc** [comment]
Thank you - closing issue as resolved :)
