### ISSUE TITLE
Line terminators in gradlew

### ISSUE THREAD

**Issue by satta** [enasequence/sequencetools#10]
Hi,

the `gradlew` wrapper has DOS line endings:
```
$ file gradlew
gradlew: a bash\015 script, ASCII text executable, with CRLF line terminators
```
which leads to problems trying to execute it:
```
$ chmod +x gradlew; ./gradlew
: No such file or directory
```
It would be nice if you could use UNIX line endings -- thanks!
A simple `dos2unix` did it for me:
```
$ dos2unix gradlew
dos2unix: converting file gradlew to Unix format ...
$ chmod +x gradlew; ./gradlew
Downloading http://services.gradle.org/distributions/gradle-1.11-all.zip
.....
```

**Comment by kethireddy** [comment]
Could you please try using the gradlew from  new version of sequencetools : 

https://github.com/enasequence/sequencetools/releases/tag/v1.1.139

**Comment by satta** [comment]
Thanks for updating the repo and tagging a new release! 👍  

Looking better now:
```
$ file gradlew
gradlew: a bash script, ASCII text executable
```
