### ISSUE TITLE
Validation of dates in FlatFile genome annotations failing with system locale set to sv_SE 

### ISSUE THREAD

**Issue by wna-se** [enasequence/sequencetools#132]
Running validation on a FlatFile genome annotations with system locale set to sv_SE will fail with `ERROR: Invalid date: 23-FEB-2023 [ line: 9]`. Changing the locale to en_UK (e.g. `java -Duser.language=en -Duser.country=UK`) and running the same command will pass the validation without the error.

In [FlatFileUtils.java](https://github.com/enasequence/sequencetools/blob/4ecf1c2197d9828a1bb32faabf31ad67e77bdcc4/src/main/java/uk/ac/ebi/embl/flatfile/FlatFileUtils.java#L236) I see that the defaultLocale is set to UK on line 236 and I assume this should happen before or as the dateMonYear object created (e.g. n`ew SimpleDateFormat("dd-MMM-yyyy", Locale.UK)`).

**Comment by raskoleinonen** [comment]
Replicated the problem and prepared a fix:
https://github.com/enasequence/sequencetools/pull/135

Pending approval and integration testing.

**Comment by raskoleinonen** [comment]
The locale problem affecting dates has been fixed by using DateTimeFormatter (threadsafe) and setting the locale to UK. 
https://github.com/enasequence/sequencetools/commit/dfbc6cd10083b6fa109bb3aec977ef13d6cec0b5
