### ISSUE TITLE
Dependency "uk.ac.ebi.ena:webin-era-service-sdk:3.4.1" not publicly available

### ISSUE THREAD

**Issue by wna-se** [enasequence/sequencetools#133]
The dependency `uk.ac.ebi.ena:webin-era-service-sdk:3.4.1` that was added in version 2.11.3 is not publicly available and prevents me from building without having a private token for the `https://gitlab.ebi.ac.uk/api/v4/projects/811/packages/maven` repository. 

Suggested solution: 1) Make the dependency publicly available or 2) provide instructions on how to get a private token for the repository providing the dependency.

**Comment by raskoleinonen** [comment]
This is an oversight. Sequecetools should only use publicly available HTTPS endpoints. However, webin-era-service-sdk is a client for EBI-internal HTTPS endpoints. We'll talk about what to do with this (internal ticket ENA-5477).

**Comment by raskoleinonen** [comment]
The dependency has been removed:
https://github.com/enasequence/sequencetools/commit/b35671ac40db5c8d6d17076a92e9a54efd66af8c
