### ISSUE TITLE
Update build instructions to require Gradle version below 7

### ISSUE THREAD

**Issue by wna-se** [enasequence/sequencetools#134]
Gradle 7 introduced several deprecations that prevents the project to be built using the current `build.gradle`. Consider updating the build instructions to reflect this.

**Comment by raskoleinonen** [comment]
We'll talk about what to do with this (internal ticket ENA-5478).

**Comment by raskoleinonen** [comment]
The build instructions in the wiki were out of date and not maintained. I have removed them. No build instructions are provided at this time.
