### ISSUE TITLE
Scientific_name is not submittable (MasterEntrySourceCheck_2) 

### ISSUE THREAD

**Issue by peterjc** [enasequence/sequencetools#15]
I am trying to submit a previously un-described bacteria strain to the ENA, which is not in the NCBI taxonomy. We are referring to it using the pattern "Serratia sp. XYZ" where XYZ is the strain name. I have done this successfully in the past with a different genus, so suspect the validator as been made stricter since.

I have tried both Taxon ID 613 which is "Serratia",

https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=613&lvl=3&lin=f&keep=1&srchmode=1&unlock

and Taxon ID 616 which is "Serratia sp.", see https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=616&lvl=5&lin=f&keep=1&srchmode=1&unlock

What do these error messages from the ENA validator mean?

```
$ java -jar embl-api-validator-1.1.149.jar XYZ.embl
...
ERROR: Scientific_name "Serratia sp." is not submittable. (MasterEntrySourceCheck_2)  line: 1 of XYZ.embl
ERROR: At least one of the following qualifiers "strain, environmental_sample, isolate" must exist when organism belongs to Bacteria. (OrganismAndRequiredQualifierCheck)  line: 17 of XYZ.embl
...
```

Here the EMBL file contained:

```
FT   source          1..5090820
FT                   /organism="Serratia sp."
FT                   /mol_type="genomic DNA"
FT                   /db_xref="taxon:616"
FT                   /note="gnl|...
```

Adding a line like this to the source feature solves the second message:

```
FT                   /strain="XYZ"
```

However I do not understand the complaint about the species name. Tracing the code, ``MasterEntrySourceCheck_2`` relates to ``MASTER_ENTRY_ORGANISM_MESSAGE_ID`` which appears to cross-check the taxonomy ID and the species name:

https://github.com/enasequence/sequencetools/blob/31a426efbb51c88d9a64e94a6eb753f69e5d6c77/embl-api-core/src/main/java/uk/ac/ebi/embl/api/validation/check/entry/MasterEntrySourceCheck.java#L35

How should this situation be described to pass validation?

See also: https://github.com/sanger-pathogens/gff3toembl/issues/71

**Comment by peterjc** [comment]
In comment https://github.com/sanger-pathogens/gff3toembl/issues/71#issuecomment-262805530 @andrewjpage says this is likely related to a policy change about high level taxa and novel species.

**Comment by kethireddy** [comment]
Hi Peter,

Sorry, I deployed the validator with wrong validationscope i.e. ASSEMBLY_MASTER( it should be EMBL).

I will fix it and let you know.

Regards,
Kethi

**Comment by peterjc** [comment]
Thanks Kethi!

**Comment by kethireddy** [comment]
Hi peter,

Fixed version of validator is here :  https://mvnrepository.com/artifact/uk.ac.ebi.ena.sequence/embl-api-validator/1.1.150

Regards,
Kethi

**Comment by peterjc** [comment]
Confirming that version 1.1.150 does not give this error for my file:

```
ERROR: Scientific_name "Serratia sp." is not submittable. (MasterEntrySourceCheck_2)
```

It still gives this error, but I can add one of these fields to the source feature(s) in my file to resolve it:

```
ERROR: At least one of the following qualifiers "strain, environmental_sample, isolate" must exist when organism belongs to Bacteria. (OrganismAndRequiredQualifierCheck)
```

Closing as resolved, thank you.
