### ISSUE TITLE
Problem when checking the Primary Accession between ID and AC lines.

### ISSUE THREAD

**Issue by Juke34** [enasequence/sequencetools#16]
My primary accession was identical but I got this error message using the embl flat file validator embl-api-validator-1.1.156.jar:
ERROR: primary accession number is given on both the ID and AC lines must be the same. (AC.1)  line: 3
I found that the problem was due to the fact that my accession numbers were both in lowercase.
I digged a bit and I have seen that I can have lowercase characters into the accession number of the ID line but, if I have one lowercase character within the accession number of the AC line the error occurs. 
Could it be fixed ?

**Comment by kethireddy** [comment]
https://github.com/enasequence/sequencetools/commit/dc54cb00a7c6563473c3885a1f2f42d1a00d3b35

it's fixed and will be included in next version of validator

**Comment by Juke34** [comment]
Excellent !
