### ISSUE TITLE
Where are the relases gone?

### ISSUE THREAD

**Issue by sklages** [enasequence/sequencetools#56]
Not sure, where to get a current release? Building from source did not work out-of-the-box.
Any other recommended way to validate my EMBL file(s)?

**Comment by raskoleinonen** [comment]
My apologies for this very late reply. Sequencetools is no longer deployed as a standalone tool. Instead it is deployed as part of the Webin-CLI command line program that can validate flat files, for example, when using the -context=sequence and -validate options.

More information about Webin-cli can be found from:

https://ena-docs.readthedocs.io/en/latest/submit/general-guide/webin-cli.html
and
https://github.com/enasequence/webin-cli
