### ISSUE TITLE
Invalid file triggers NullPointerException

### ISSUE THREAD

**Issue by satta** [enasequence/sequencetools#9]
When trying to process an invalid 'EMBL-like' file, the validator sometimes produces a Java exception instead of delivering more useful messages. Here's an example:

```
$ curl ftp://ftp.sanger.ac.uk/pub/project/pathogens/Plasmodium/P_vivaxP01/version_1/2016/August_2016/PvP01_05_v1.embl.gz | gunzip > PvP01_05_v1.embl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  648k  100  648k    0     0   347k      0  0:00:01  0:00:01 --:--:--  347k
$ java -jar ./embl-api-validator/build/libs/embl-api-validator-1.1.131.jar PvP01_05_v1.embl     
uk.ac.ebi.embl.api.validation.ValidationEngineException: uk.ac.ebi.embl.api.validation.ValidationEngineException: java.lang.NullPointerException
    at uk.ac.ebi.embl.api.validation.plan.EmblEntryValidationPlan.execute(EmblEntryValidationPlan.java:120)
    at uk.ac.ebi.embl.api.validation.plan.EmblEntryValidationPlan.execute(EmblEntryValidationPlan.java:143)
    at uk.ac.ebi.embl.api.validation.EnaValidator.validateEntry(EnaValidator.java:1009)
    at uk.ac.ebi.embl.api.validation.EnaValidator.validateEntriesInReader(EnaValidator.java:722)
    at uk.ac.ebi.embl.api.validation.EnaValidator.validateFile(EnaValidator.java:526)
    at uk.ac.ebi.embl.api.validation.EnaValidator.validateFiles(EnaValidator.java:363)
    at uk.ac.ebi.embl.api.validation.EnaValidator.main(EnaValidator.java:173)
Caused by: uk.ac.ebi.embl.api.validation.ValidationEngineException: java.lang.NullPointerException
    at uk.ac.ebi.embl.api.validation.check.feature.EC_numberCheck.check(EC_numberCheck.java:51)
    at uk.ac.ebi.embl.api.validation.check.feature.EC_numberCheck.check(EC_numberCheck.java:25)
    at uk.ac.ebi.embl.api.validation.plan.ValidationPlan.execute(ValidationPlan.java:196)
    at uk.ac.ebi.embl.api.validation.plan.EmblEntryValidationPlan.executeChecksandFixes(EmblEntryValidationPlan.java:165)
    at uk.ac.ebi.embl.api.validation.plan.EmblEntryValidationPlan.execute(EmblEntryValidationPlan.java:115)
    ... 6 more
Caused by: java.lang.NullPointerException
    at uk.ac.ebi.embl.api.validation.check.feature.EC_numberCheck.check(EC_numberCheck.java:47)
    ... 10 more
VALIDATOR FAILING
```

Here are the `VAL_*.txt` files created by this call: https://www.dropbox.com/s/faii78k11cbzz8k/validator_VAL_files.tar.gz?dl=0

I would have expected the call to finish and providing a complete list of errors for this file.

I can confirm that the validator works well in general and as expected for other files:

```
$ curl https://www.ebi.ac.uk/ena/data/view/AACH01000026%26display%3Dtext > test.embl     
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 26452    0 26452    0     0  90576      0 --:--:-- --:--:-- --:--:-- 90589
$ java -jar ./embl-api-validator/build/libs/embl-api-validator-1.1.131.jar test.embl 


Messages
WARNING: Sequence contains a stretch of n characters between base 9,497 and 9,497 that is not represented with a "gap" feature (stretches of n greater than 0 gives a warning, greater than 10 gives an error). (SequenceToGapFeatureBasesCheck-1)  line: 59-363 of test.embl
WARNING: Sequence contains a stretch of n characters between base 9,497 and 9,497 that is not represented with a "gap" feature (stretches of n greater than 0 gives a warning, greater than 10 gives an error). (SequenceToGapFeatureBasesCheck-1)  line: 59-363 of test.embl

***FILE SUMMARY***
test.embl - 1 entries, 0 failed entries, 0 errors, 0 fixes, 2 warnings & info

*** SUMMARY***
Fixed Entries:0
Failed Entries:0
Checked Entries:1
Unchanged Entries:1


Processed 1 entries in 0 seconds.
```

So I think it might just be the specific kind of error in the first file?

**Comment by bastian-wur** [comment]
+1, have the same here.
Tried to validate a file, which already passed through an earlier version of the validator (no idea which version, was downloaded 17.07.2014), and I get this error.
With the previous validator this normally indicated that the header didn't look as it should.
Currently mine is:
ID   XXX; SV XXX; LINEAR; genomic DNA; WGS; PRO;  4793626 BP.

Maybe a pointer how it should look like would be helpful.

**Comment by kethireddy** [comment]
fixed the source code : https://github.com/enasequence/sequencetools/commit/2e1ed83f34494bece05cbfcb4e57a81fba70c35d

**Comment by bastian-wur** [comment]
Okay, works now :).

I now get as only error in the file:
ERROR: Submitter references are mandatory in EMBL-BANK entries line: 1 of My.embl
I get this for all the ID lines.
The ID is exactly as above, and if I check ftp://ftp.ebi.ac.uk/pub/databases/embl/doc/FT_current.txt then the ID line looks correct.
Right now not sure if I'm overlooking something or if the error is incorrect.

**Comment by satta** [comment]
BTW @kethireddy do you think your fix in 2e1ed83 would merit a new release or would you like to wait until @bastian-wur's issue has been addressed?

**Comment by kethireddy** [comment]
@bastian-wur  "ERROR: Submitter references are mandatory in EMBL-BANK entries " is a entry specific content error, so the line number always point to the beginning of the entry i.e. ID line.

@satta new release "https://github.com/enasequence/sequencetools/releases/tag/v1.1.133" is available with this fix : https://github.com/enasequence/sequencetools/commit/2e1ed83f34494bece05cbfcb4e57a81fba70c35d

**Comment by satta** [comment]
@kethireddy excellent, many thanks -- from my side this issue can be closed!
